[package]
name = "qckchk"
version = "0.1.0"
authors = ["Graham Dennis <graham.dennis@gmail.com>"]

[dependencies]
rand = "0.3"
rand-distributions = "0.1"
num = "0.1"
env_logger = "0.3"
log = "0.3"

[features]
default = []
no_function_casts = []
